### ISSUE TITLE
Documenting article is not part of the repository

### ISSUE THREAD

**Issue by Jack28** [SgtMate/container_escape_showcase#4]
The article you wrote (in German) is not part of the repository.

I would expect to find it here.

Even though it is "only" in German I think it should be included.

**Comment by SgtMate** [comment]
Oh, great idea! I didn't think about that. 
I'll add an export of the article.

The link to the wiki would not be helpful since the access is restricted.

**Comment by SgtMate** [comment]
I added an export of the article and linked it in the README.
